# ==========================================
# 基础网络与性能设置 (General)
# ==========================================
mixed-port: 7890                 # 混合端口，同时支持 HTTP 和 SOCKS5
allow-lan: true                  # 允许局域网设备(如手机/iPad)连接此代理
unified-delay: true              # 使用真实 HTTP 响应时间作为测速延迟，而不是虚假的 TCP 握手时间
tcp-concurrent: true             # 并发连接域名的所有 IP，极大提升首次加载速度
log-level: info                  # 日志级别：打印重要连接信息，不影响性能
find-process-mode: always        # 始终追踪发起网络连接的具体进程名
bind-address: "*"                # 监听所有网络接口

# ==========================================
# 全局接管设置 (TUN 模式)
# ==========================================
tun:
  enable: true                   # 开启虚拟网卡，实现所有流量的全局接管
  stack: mixed                   # TCP 用系统栈，UDP 用 gVisor 栈，兼顾性能与兼容
  dns-hijack:
    - any:53                     # 强制劫持系统 53 端口的所有传统 DNS 请求，送入内置 DNS 处理
  mtu: 1500                      # 虚拟网卡最大传输单元，标准 1500

# ==========================================
# 防泄露与 DNS 分流设置 (DNS)
# ==========================================
dns:
  enable: true                   # 开启内置 DNS 服务器
  ipv6: false                    # 关闭 IPv6 解析，防止本地宽带 IPv6 导致流量直连泄露
  enhanced-mode: fake-ip         # 开启 Fake-IP 伪装模式，彻底杜绝本地 DNS 泄露
  fake-ip-range: 198.18.0.1/16   # 伪装 IP 的生成网段 (内网保留网段)
  fake-ip-filter:                # Fake-IP 白名单：以下域名返回真实 IP
    - '*.lan'                    # 局域网设备
    - '*.local'                  # 本地网络设备
    - 'time.*.com'               # 时间同步服务器
    - 'ntp.*.com'                # 网络时间协议服务器
    - '+.market.xiaomi.com'      # 小米应用商店(特定网络需求)
    - 'localhost.ptlogin2.qq.com'# 腾讯系软件快捷登录必备回环域名
  use-hosts: true                # 尊重操作系统的 /etc/hosts 记录
  default-nameserver:            # 启动 DNS：仅用于解析下方 DoH 链接本身的真实 IP
    - 119.29.29.29
    - 223.5.5.5
  nameserver:                    # 默认 DNS：解析非国内域名 (强制通过代理节点走，防污染)
    - https://1.1.1.1/dns-query#🚀 节点选择
    - https://8.8.8.8/dns-query#🚀 节点选择
  nameserver-policy:             # DNS 分流策略：精准匹配国内域名
    "geosite:cn":                # 只要是中国域名，就直接发给国内腾讯/阿里 DoH 解析 (极速直连)
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

# ==========================================
# 流量嗅探与纠错设置 (Sniffer)
# ==========================================
sniffer:
  enable: true                   # 开启流量嗅探，应对软件直接通过纯 IP 发起连接的情况
  parse-pure-ip: true            # 强行解析纯 IP 请求，尝试从中提取真实域名
  force-dns-mapping: true        # 强制将嗅探到的域名与 Fake-IP 对应，防止分流规则失效
  sniff:                         # 指定嗅探的协议与端口
    HTTP:
      ports:
        - 80
        - 443
    TLS:
      ports:
        - 443
  skip-domain:                   # 嗅探白名单：排除特定域名的嗅探
    - +.push.apple.com           # 放行苹果推送服务，防止消息通知断连或收不到